version: '3.1'

services:   
  postgre:
    environment:
      MYSQL_DATABASE: cobi
      MYSQL_USER: cobi
      MYSQL_PASSWORD: cobi
      MYSQL_ROOT_PASSWORD: cobi  
  webapp:
    environment:
      - ENV: production