version: '3.3'

services:
  webadmin:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./webadmin/app:/var/www/app
      - ./nginx-config/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - redis
      - postgre
  fpm:
    build:
      context: ./fpm
    restart: always
    volumes:
      - ./webadmin/app:/var/www/app
    links:
      - postgre
      - redis    
  postgre:
    image: postgres:10.2
    restart: always
    ports:
      - "5432:5432"  
  redis:
    image: redis:4.0-alpine
    ports:
      - "16379:6379"
  webapp:
    build:
      context: ./webapp
    volumes:
      - ./webapp/app:/usr/src/app
      - ./webapp/dist:/usr/src/dist
    depends_on:
      - redis
      - postgre
      - fpm
    links:
      - redis
      - postgre
    ports:
      - "3000:8000"   

