version: '3.3'

services:
  webadmin:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./webadmin/app:/var/www/app
      - ./nginx-config/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - redis
      - core_database
  fpm:
    build:
      context: ./fpm
    restart: always
    volumes:
      - ./webadmin/app:/var/www/app
    links:
      - core_database
      - redis    
  core_database:
    container_name: core_database
    image: postgres:10.2
    restart: always
    ports:
      - "5432:5432"  
  redis:
    container_name: redis
    image: redis:4.0-alpine
    ports:
      - "6379:6379"  

